#!/bin/bash

python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_average.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_average.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_emoji_vecmap.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_emoji_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_emoji_weighted.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_emoji_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_homographs_vecmap.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_homographs_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_homographs_weighted.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_homographs_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_identical_meemi.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_identical_meemi.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_identical_muse.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_identical_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_identical_vecmap.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_identical_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_numerals_vecmap.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_numerals_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_numerals_weighted.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_numerals_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_unsupervised_muse.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_unsupervised_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_weighted_average.txt > ../results/german/sb10k67/cross_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_weighted_average.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_average.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_average.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_emoji_vecmap.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_emoji_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_emoji_weighted.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_emoji_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_homographs_vecmap.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_homographs_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_homographs_weighted.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_homographs_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_identical_meemi.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_identical_meemi.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_identical_muse.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_identical_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_identical_vecmap.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_identical_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_numerals_vecmap.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_numerals_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_numerals_weighted.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_numerals_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_unsupervised_muse.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_unsupervised_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_weighted_average.txt > ../results/german/sb10k67/cross_english_german_semeval_sbk1067_lstm_collados_english_german_weighted_average.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_average.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_average.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_emoji_vecmap.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_emoji_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_emoji_weighted.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_emoji_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_homographs_vecmap.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_homographs_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_homographs_weighted.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_homographs_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_identical_meemi.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_identical_meemi.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_identical_muse.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_identical_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_identical_vecmap.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_identical_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_numerals_vecmap.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_numerals_vecmap.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_numerals_weighted.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_numerals_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_unsupervised_muse.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_unsupervised_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_weighted_average.txt > ../results/german/sb10k67/cross_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_weighted_average.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/mono_german_sbk1067_bilabel_lstm_collados_german.txt > ../results/german/sb10k67/mono_german_sbk1067_bilabel_lstm_collados_german.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/mono_german_sbk1067_bilabel_svm_collados_german.txt > ../results/german/sb10k67/mono_german_sbk1067_bilabel_svm_collados_german.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/mono_german_sbk1067_lstm_collados_german.txt > ../results/german/sb10k67/mono_german_sbk1067_lstm_collados_german.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/mono_german_sbk1067_svm_collados_german.txt > ../results/german/sb10k67/mono_german_sbk1067_svm_collados_german.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/multi_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_mono.txt > ../results/german/sb10k67/multi_english_german_semeval_bilabel_sbk1067_lstm_collados_english_german_mono.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/multi_english_german_semeval_bilabel_sbk1067_lstm_collados_english.txt > ../results/german/sb10k67/multi_english_german_semeval_bilabel_sbk1067_lstm_collados_english.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/multi_english_german_semeval_sbk1067_lstm_collados_english_german_mono.txt > ../results/german/sb10k67/multi_english_german_semeval_sbk1067_lstm_collados_english_german_mono.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/multi_english_german_semeval_sbk1067_lstm_collados_english.txt > ../results/german/sb10k67/multi_english_german_semeval_sbk1067_lstm_collados_english.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/multi_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_mono.txt > ../results/german/sb10k67/multi_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english_german_mono.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/sb10k67/multi_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english.txt > ../results/german/sb10k67/multi_english_german_semevalNegative_bilabel_sbk1067_lstm_collados_english.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semeval_bilabel_sbk10_lstm_collados_english_german_emoji_weighted.txt > ../results/german/cross_english_german_semeval_bilabel_sbk10_lstm_collados_english_german_emoji_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semeval_bilabel_sbk10_lstm_collados_english_german_homographs_weighted.txt > ../results/german/cross_english_german_semeval_bilabel_sbk10_lstm_collados_english_german_homographs_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semeval_bilabel_sbk10_lstm_collados_english_german_identical_muse.txt > ../results/german/cross_english_german_semeval_bilabel_sbk10_lstm_collados_english_german_identical_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semeval_bilabel_sbk10_lstm_collados_english_german_unsupervised_muse.txt > ../results/german/cross_english_german_semeval_bilabel_sbk10_lstm_collados_english_german_unsupervised_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semeval_sbk10_lstm_collados_english_german_emoji_weighted.txt > ../results/german/cross_english_german_semeval_sbk10_lstm_collados_english_german_emoji_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semeval_sbk10_lstm_collados_english_german_homographs_weighted.txt > ../results/german/cross_english_german_semeval_sbk10_lstm_collados_english_german_homographs_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semeval_sbk10_lstm_collados_english_german_identical_muse.txt > ../results/german/cross_english_german_semeval_sbk10_lstm_collados_english_german_identical_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semeval_sbk10_lstm_collados_english_german_unsupervised_muse.txt > ../results/german/cross_english_german_semeval_sbk10_lstm_collados_english_german_unsupervised_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_emoji_weighted.txt > ../results/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_emoji_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_homographs_weighted.txt > ../results/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_homographs_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_identical_muse.txt > ../results/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_identical_muse.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_numerals_weighted.txt > ../results/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_numerals_weighted.txt
echo "Finish"
python3 senti_cross_embeddings.py ../config/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_unsupervised_muse.txt > ../results/german/cross_english_german_semevalNegative_bilabel_sbk10_lstm_collados_english_german_unsupervised_muse.txt
echo "Finish"
echo "Finish del todo"